Update pylint.yml

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -52,7 +52,11 @@ jobs:
       if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
 
     - name: Run tests
-      run: poetry run pytest
+      run: |
+        poetry run pytest
+        if [ $? -eq 1 ]; then
+          echo "One or more unit tests have failed"
+        fi
 
     # - name: Install dependencies
     #   run: |
